export type BusinessUnit = 'Audit' | 'Tax' | 'Consulting';
export type EngagementStatus = 'Active' | 'Completed' | 'Proposed' | 'On Hold';
export type ContactSide = 'Firm' | 'Client';
export type BillingArrangement = 'Fixed Fee' | 'Time & Materials' | 'Retainer';

export interface Engagement {
  id: string;
  client: string;
  industry: string;
  engagementName: string;
  businessUnit: BusinessUnit;
  serviceType: string;
  status: EngagementStatus;
  partnerId: string;
  managerId: string;
  teamIds: string[];
  clientContactIds: string[];
  revenueK: number;
  startDate: string;
  endDate: string;
  billingArrangement: BillingArrangement;
  office: string;
  notes: string;
}

export interface Contact {
  id: string;
  name: string;
  title: string;
  company: string;
  side: ContactSide;
  email: string;
  phone: string;
  location: string;
  department: string;
  level: string;
}

export const CONTACTS: Contact[] = [
  // Nexus Advisory Group — Digital Assets Practice
  { id: 'nxg-001', name: 'Rachel Chen',        title: 'Partner',            company: 'Nexus Advisory Group', side: 'Firm', email: 'r.chen@nexusadvisory.com',        phone: '', location: 'New York, NY',    department: 'Financial Services',   level: 'Partner' },
  { id: 'nxg-002', name: 'Daniel Park',         title: 'Partner',            company: 'Nexus Advisory Group', side: 'Firm', email: 'd.park@nexusadvisory.com',         phone: '', location: 'New York, NY',    department: 'Financial Services',   level: 'Partner' },
  { id: 'nxg-003', name: 'Steven Wallace',      title: 'Partner',            company: 'Nexus Advisory Group', side: 'Firm', email: 's.wallace@nexusadvisory.com',      phone: '', location: 'New York, NY',    department: 'AML / Compliance',     level: 'Partner' },
  { id: 'nxg-004', name: 'Laura Morgan',        title: 'Managing Director',  company: 'Nexus Advisory Group', side: 'Firm', email: 'l.morgan@nexusadvisory.com',       phone: '', location: 'New York, NY',    department: 'Financial Services',   level: 'Managing Director' },
  { id: 'nxg-005', name: 'Brian Torres',        title: 'Managing Director',  company: 'Nexus Advisory Group', side: 'Firm', email: 'b.torres@nexusadvisory.com',       phone: '', location: 'New York, NY',    department: 'Financial Services',   level: 'Managing Director' },
  { id: 'nxg-006', name: 'Emily Hartwell',      title: 'Partner',            company: 'Nexus Advisory Group', side: 'Firm', email: 'e.hartwell@nexusadvisory.com',     phone: '', location: 'Chicago, IL',     department: 'Consulting',           level: 'Partner' },
  { id: 'nxg-007', name: 'James Okafor',        title: 'Managing Director',  company: 'Nexus Advisory Group', side: 'Firm', email: 'j.okafor@nexusadvisory.com',       phone: '', location: 'Chicago, IL',     department: 'Consulting',           level: 'Managing Director' },
  { id: 'nxg-008', name: 'Priya Kapoor',        title: 'Partner',            company: 'Nexus Advisory Group', side: 'Firm', email: 'p.kapoor@nexusadvisory.com',       phone: '', location: 'New York, NY',    department: 'BSA / AML',            level: 'Partner' },
  { id: 'nxg-009', name: 'Marcus Webb',         title: 'Partner',            company: 'Nexus Advisory Group', side: 'Firm', email: 'm.webb@nexusadvisory.com',         phone: '', location: 'New York, NY',    department: 'BSA / AML',            level: 'Partner' },
  { id: 'nxg-010', name: 'Sandra Nguyen',       title: 'Partner',            company: 'Nexus Advisory Group', side: 'Firm', email: 's.nguyen@nexusadvisory.com',       phone: '', location: 'Chicago, IL',     department: 'Risk Advisory',        level: 'Partner' },
  { id: 'nxg-011', name: 'Kevin Delano',        title: 'Partner',            company: 'Nexus Advisory Group', side: 'Firm', email: 'k.delano@nexusadvisory.com',       phone: '', location: 'Dallas, TX',      department: 'Financial Services',   level: 'Partner' },
  { id: 'nxg-012', name: 'Alicia Freed',        title: 'Senior Manager',     company: 'Nexus Advisory Group', side: 'Firm', email: 'a.freed@nexusadvisory.com',        phone: '', location: 'Dallas, TX',      department: 'Financial Services',   level: 'Senior Manager' },
  { id: 'nxg-013', name: 'Thomas Reeves',       title: 'Partner',            company: 'Nexus Advisory Group', side: 'Firm', email: 't.reeves@nexusadvisory.com',       phone: '', location: 'Charlotte, NC',   department: 'Audit',                level: 'Partner' },
  { id: 'nxg-014', name: 'Jasmine Patel',       title: 'Senior Manager',     company: 'Nexus Advisory Group', side: 'Firm', email: 'j.patel@nexusadvisory.com',        phone: '', location: 'Phoenix, AZ',     department: 'Tax',                  level: 'Senior Manager' },
  { id: 'nxg-015', name: 'Nicholas Hartmann',   title: 'Partner',            company: 'Nexus Advisory Group', side: 'Firm', email: 'n.hartmann@nexusadvisory.com',     phone: '', location: 'Chicago, IL',     department: 'Financial Services',   level: 'Partner' },
  { id: 'nxg-016', name: 'Carla Bennett',       title: 'Partner',            company: 'Nexus Advisory Group', side: 'Firm', email: 'c.bennett@nexusadvisory.com',      phone: '', location: 'Chicago, IL',     department: 'AML / Compliance',     level: 'Partner' },
  { id: 'nxg-017', name: 'Diana Liu',           title: 'Senior Manager',     company: 'Nexus Advisory Group', side: 'Firm', email: 'd.liu@nexusadvisory.com',          phone: '', location: 'New York, NY',    department: 'Audit',                level: 'Senior Manager' },
  { id: 'nxg-018', name: 'Robert Flanagan',     title: 'Partner',            company: 'Nexus Advisory Group', side: 'Firm', email: 'r.flanagan@nexusadvisory.com',     phone: '', location: 'Chicago, IL',     department: 'Advisory',             level: 'Partner' },
  { id: 'nxg-019', name: 'Megan Stokes',        title: 'Senior Manager',     company: 'Nexus Advisory Group', side: 'Firm', email: 'm.stokes@nexusadvisory.com',       phone: '', location: 'Chicago, IL',     department: 'Audit',                level: 'Senior Manager' },
  { id: 'nxg-020', name: 'Patricia Elmore',     title: 'Partner',            company: 'Nexus Advisory Group', side: 'Firm', email: 'p.elmore@nexusadvisory.com',       phone: '', location: 'Charlotte, NC',   department: 'Audit',                level: 'Partner' },
  { id: 'nxg-021', name: 'Samantha Vega',       title: 'Senior Manager',     company: 'Nexus Advisory Group', side: 'Firm', email: 's.vega@nexusadvisory.com',         phone: '', location: 'Dallas, TX',      department: 'Audit',                level: 'Senior Manager' },
  { id: 'nxg-022', name: 'Warren Jacobs',       title: 'Partner',            company: 'Nexus Advisory Group', side: 'Firm', email: 'w.jacobs@nexusadvisory.com',       phone: '', location: 'Chicago, IL',     department: 'Risk Advisory',        level: 'Partner' },
  { id: 'nxg-023', name: 'Christine Fuller',    title: 'Senior Manager',     company: 'Nexus Advisory Group', side: 'Firm', email: 'c.fuller@nexusadvisory.com',       phone: '', location: 'New York, NY',    department: 'Consulting',           level: 'Senior Manager' },
  { id: 'nxg-024', name: 'Andrew Kim',          title: 'Partner',            company: 'Nexus Advisory Group', side: 'Firm', email: 'a.kim@nexusadvisory.com',          phone: '', location: 'Chicago, IL',     department: 'Financial Services',   level: 'Partner' },
  { id: 'nxg-025', name: 'George Ashworth',     title: 'Partner',            company: 'Nexus Advisory Group', side: 'Firm', email: 'g.ashworth@nexusadvisory.com',     phone: '', location: 'Chicago, IL',     department: 'IT Assurance',         level: 'Partner' },
  { id: 'nxg-026', name: 'Natalie Cross',       title: 'Senior Manager',     company: 'Nexus Advisory Group', side: 'Firm', email: 'n.cross@nexusadvisory.com',        phone: '', location: 'New York, NY',    department: 'AML / Compliance',     level: 'Senior Manager' },
  { id: 'nxg-027', name: 'Victoria Medina',     title: 'Senior Manager',     company: 'Nexus Advisory Group', side: 'Firm', email: 'v.medina@nexusadvisory.com',       phone: '', location: 'New York, NY',    department: 'AML / Compliance',     level: 'Senior Manager' },
  { id: 'nxg-028', name: 'Philip Drummond',     title: 'Partner',            company: 'Nexus Advisory Group', side: 'Firm', email: 'p.drummond@nexusadvisory.com',     phone: '', location: 'Chicago, IL',     department: 'Risk Advisory',        level: 'Partner' },
  { id: 'nxg-029', name: 'Helen Greer',         title: 'Partner',            company: 'Nexus Advisory Group', side: 'Firm', email: 'h.greer@nexusadvisory.com',        phone: '', location: 'New York, NY',    department: 'Audit',                level: 'Partner' },
  { id: 'nxg-030', name: 'Joseph Caldwell',     title: 'Partner',            company: 'Nexus Advisory Group', side: 'Firm', email: 'j.caldwell@nexusadvisory.com',     phone: '', location: 'Columbus, OH',    department: 'Financial Services',   level: 'Partner' },

  // Client Contacts
  { id: 'cl-001', name: 'Adrian Hollis',         title: 'Chief Compliance Officer',                company: 'Summit Bridge Bank',         side: 'Client', email: 'a.hollis@summitbridgebank.com',       phone: '', location: 'Hoboken, NJ',        department: 'Compliance',      level: 'C-Suite' },
  { id: 'cl-002', name: 'Fiona Drummond',        title: 'Chief Risk Officer',                      company: 'Summit Bridge Bank',         side: 'Client', email: 'f.drummond@summitbridgebank.com',     phone: '', location: 'Hoboken, NJ',        department: 'Risk',            level: 'C-Suite' },
  { id: 'cl-003', name: 'Walter Sinclair',       title: 'CFO & EVP Risk & Operations',            company: 'Clearwater Community Bank',  side: 'Client', email: '',                                    phone: '', location: 'Wichita, KS',         department: 'Finance / Risk',  level: 'C-Suite' },
  { id: 'cl-004', name: 'Patricia Nolan',        title: 'Chief Compliance Officer',                company: 'Veriblock Trust',            side: 'Client', email: 'p.nolan@veriblocktrust.com',          phone: '', location: 'New York, NY',      department: 'Compliance',      level: 'C-Suite' },
  { id: 'cl-005', name: 'Evan Stark',            title: 'Chief Risk Officer',                      company: 'Veriblock Trust',            side: 'Client', email: '',                                    phone: '', location: 'New York, NY',      department: 'Risk',            level: 'C-Suite' },
  { id: 'cl-006', name: 'Lena Fairchild',        title: 'Chief Compliance Officer',                company: 'Veriblock Trust',            side: 'Client', email: '',                                    phone: '', location: 'New York, NY',      department: 'Compliance',      level: 'C-Suite' },
  { id: 'cl-007', name: 'Marco Delgado',         title: 'Chief Executive Officer',                 company: 'Fluxpay Inc.',               side: 'Client', email: 'm.delgado@fluxpay.io',                phone: '', location: 'San Mateo, CA',      department: 'Executive',       level: 'C-Suite' },
  { id: 'cl-008', name: 'Serena Molinari',       title: 'Chief Compliance Officer',                company: 'Fluxpay Inc.',               side: 'Client', email: 's.molinari@fluxpay.io',               phone: '', location: 'San Mateo, CA',      department: 'Compliance',      level: 'C-Suite' },
  { id: 'cl-009', name: 'Theo Vance',            title: 'Compliance Leader',                       company: 'Fluxpay Inc.',               side: 'Client', email: '',                                    phone: '', location: 'San Mateo, CA',      department: 'Compliance',      level: 'Director' },
  { id: 'cl-010', name: 'Harriet Ashby',         title: 'Chief Compliance Officer',                company: 'Meridian Payments',          side: 'Client', email: '',                                    phone: '', location: 'New York, NY',      department: 'Compliance',      level: 'C-Suite' },
  { id: 'cl-011', name: 'Oliver Brandt',         title: 'Chief Financial Officer',                 company: 'Bastion Digital Bank',       side: 'Client', email: 'o.brandt@bastiondigital.com',         phone: '', location: 'Cheyenne, WY',       department: 'Finance',         level: 'C-Suite' },
  { id: 'cl-012', name: 'Carolyn Voss',          title: 'Chief Executive Officer',                 company: 'Bastion Digital Bank',       side: 'Client', email: 'c.voss@bastiondigital.com',           phone: '', location: 'Cheyenne, WY',       department: 'Executive',       level: 'C-Suite' },
  { id: 'cl-013', name: 'Rafael Gutierrez',      title: 'Chief Risk Officer',                      company: 'Apex Valley Bank',           side: 'Client', email: 'r.gutierrez@apexvalleybank.com',      phone: '', location: 'San Antonio, TX',    department: 'Risk',            level: 'C-Suite' },
  { id: 'cl-014', name: 'Nadia Prescott',        title: 'Compliance Executive',                    company: 'Apex Valley Bank',           side: 'Client', email: 'n.prescott@apexvalleybank.com',       phone: '', location: 'San Antonio, TX',    department: 'Compliance',      level: 'Director' },
  { id: 'cl-015', name: 'Samuel Ortega',         title: 'Chief Risk Officer',                      company: 'Apex Valley Bank',           side: 'Client', email: '',                                    phone: '', location: 'San Antonio, TX',    department: 'Risk',            level: 'C-Suite' },
  { id: 'cl-016', name: 'Claire Beaumont',       title: 'Chief Risk Officer',                      company: 'Keystone National Bank',     side: 'Client', email: '',                                    phone: '', location: 'Charlotte, NC',     department: 'Risk',            level: 'C-Suite' },
  { id: 'cl-017', name: 'Anton Richter',         title: 'Chief Risk Officer',                      company: 'Mariner Financial Group',    side: 'Client', email: '',                                    phone: '', location: 'New York, NY',      department: 'Risk',            level: 'C-Suite' },
  { id: 'cl-018', name: 'Ingrid Sorensen',       title: 'Global Head, Future of Finance',          company: 'Mariner Financial Group',    side: 'Client', email: '',                                    phone: '', location: 'New York, NY',      department: 'Strategy',        level: 'Managing Director' },
  { id: 'cl-019', name: 'Felix Garland',         title: 'Chief Risk Officer',                      company: 'Atlas Capital Group',        side: 'Client', email: '',                                    phone: '', location: 'New York, NY',      department: 'Risk',            level: 'C-Suite' },
  { id: 'cl-020', name: 'Diane Farlow',          title: 'Chief Risk Officer',                      company: 'Nexstream Payments',         side: 'Client', email: '',                                    phone: '', location: 'Purchase, NY',       department: 'Risk',            level: 'C-Suite' },
  { id: 'cl-021', name: 'Hugo Castano',          title: 'Chief Risk & Client Services Officer',    company: 'Veridian Network',           side: 'Client', email: '',                                    phone: '', location: 'San Francisco, CA',  department: 'Risk',            level: 'C-Suite' },
  { id: 'cl-022', name: 'Tara Holbrook',         title: 'Compliance Executive',                    company: 'Western Frontier Bank',      side: 'Client', email: '',                                    phone: '', location: 'Phoenix, AZ',        department: 'Compliance',      level: 'Director' },
  { id: 'cl-023', name: 'Dennis Albright',       title: 'Sr. Director, Global Payment & Trade',   company: 'Continental Trust',          side: 'Client', email: '',                                    phone: '', location: 'New York, NY',      department: 'Payments',        level: 'Director' },
  { id: 'cl-024', name: 'Priya Venkatesan',      title: 'Chief Risk Officer',                      company: 'Lakeview Financial',         side: 'Client', email: '',                                    phone: '', location: 'Columbus, OH',       department: 'Risk',            level: 'C-Suite' },
  { id: 'cl-025', name: 'Ivan Petrov',           title: 'Chief Risk Officer',                      company: 'Great Lakes Bank',           side: 'Client', email: '',                                    phone: '', location: 'Buffalo, NY',        department: 'Risk',            level: 'C-Suite' },
  { id: 'cl-026', name: 'Rebecca Harmon',        title: 'Chief Risk Officer',                      company: 'Midland Heritage Bank',      side: 'Client', email: '',                                    phone: '', location: 'Memphis, TN',        department: 'Risk',            level: 'C-Suite' },
  { id: 'cl-027', name: 'Desmond Calloway',      title: 'Chief AML Officer',                       company: 'Harborview Bank',            side: 'Client', email: 'd.calloway@harborviewbank.com',       phone: '', location: 'West Chester, PA',   department: 'AML',             level: 'C-Suite' },
  { id: 'cl-028', name: 'Simone Archer',         title: 'Chief Risk Officer',                      company: 'Harborview Bank',            side: 'Client', email: '',                                    phone: '', location: 'West Chester, PA',   department: 'Risk',            level: 'C-Suite' },
  { id: 'cl-029', name: 'Grant Whitmore',        title: 'Global Head of Financial Crime',          company: 'Rapid Ledger / Apex Bridge', side: 'Client', email: '',                                    phone: '', location: 'San Francisco, CA',  department: 'Financial Crime', level: 'Director' },
  { id: 'cl-030', name: 'Camille Dupont',        title: 'Chief Risk Officer',                      company: 'Rapid Ledger / Apex Bridge', side: 'Client', email: '',                                    phone: '', location: 'San Francisco, CA',  department: 'Risk',            level: 'C-Suite' },
  { id: 'cl-031', name: 'Jordan Westfield',      title: 'Fin Crime Investigations Manager',        company: 'Rapid Ledger / Apex Bridge', side: 'Client', email: '',                                    phone: '', location: 'San Francisco, CA',  department: 'Financial Crime', level: 'Manager' },
  { id: 'cl-032', name: 'Tyler Ashford',         title: 'Chief Risk Officer',                      company: 'ZeroVault',                  side: 'Client', email: '',                                    phone: '', location: 'Chicago, IL',        department: 'Risk',            level: 'C-Suite' },
  { id: 'cl-033', name: 'Nathan Forsythe',       title: 'Chief Legal & Compliance Officer',        company: 'ZeroVault',                  side: 'Client', email: '',                                    phone: '', location: 'Chicago, IL',        department: 'Legal',           level: 'C-Suite' },
  { id: 'cl-034', name: 'Leon Marsh',            title: 'Compliance Executive',                    company: 'PrimeEx Digital',            side: 'Client', email: '',                                    phone: '', location: 'New York, NY',      department: 'Compliance',      level: 'Director' },
  { id: 'cl-035', name: 'Bianca Kovacs',         title: 'Head of Risk',                            company: 'Pulsar Finance',             side: 'Client', email: '',                                    phone: '', location: 'New York, NY',      department: 'Risk',            level: 'Director' },
  { id: 'cl-036', name: 'Conrad Ellison',        title: 'Global Head of Compliance',               company: 'Orion Stablecoin',           side: 'Client', email: '',                                    phone: '', location: 'Boston, MA',         department: 'Compliance',      level: 'Director' },
  { id: 'cl-037', name: 'Anika Mehta',           title: 'Chief Compliance & Risk Officer',         company: 'WaveSettle',                 side: 'Client', email: '',                                    phone: '', location: 'San Francisco, CA',  department: 'Compliance',      level: 'C-Suite' },
  { id: 'cl-038', name: 'Dylan Roark',           title: 'Crypto Compliance Executive',             company: 'WaveSettle',                 side: 'Client', email: '',                                    phone: '', location: 'San Francisco, CA',  department: 'Compliance',      level: 'Director' },
  { id: 'cl-039', name: 'Gina Harrington',       title: 'Chief Compliance Officer',                company: 'IronSafe Digital',           side: 'Client', email: '',                                    phone: '', location: 'Palo Alto, CA',       department: 'Compliance',      level: 'C-Suite' },
  { id: 'cl-040', name: 'Miles Donovan',         title: 'Chief Compliance Officer',                company: 'Vaultstone Digital',         side: 'Client', email: '',                                    phone: '', location: 'San Francisco, CA',  department: 'Compliance',      level: 'C-Suite' },
  { id: 'cl-041', name: 'Kira Sandoval',         title: 'Chief Compliance & Risk Officer',         company: 'NovaBanc',                   side: 'Client', email: '',                                    phone: '', location: 'San Francisco, CA',  department: 'Compliance',      level: 'C-Suite' },
  { id: 'cl-042', name: 'Brett Holloway',        title: 'Chief Compliance Officer',                company: 'Pinnacle National Bank',     side: 'Client', email: '',                                    phone: '', location: 'Pittsburgh, PA',      department: 'Compliance',      level: 'C-Suite' },
  { id: 'cl-043', name: 'Yolanda Reiss',         title: 'Chief Risk Officer',                      company: 'VoltChain',                  side: 'Client', email: '',                                    phone: '', location: 'Los Angeles, CA',     department: 'Risk',            level: 'C-Suite' },
  { id: 'cl-044', name: 'Elliot Graves',         title: 'Chief Risk Officer',                      company: 'Union Federal Bank',         side: 'Client', email: '',                                    phone: '', location: 'New York, NY',      department: 'Risk',            level: 'C-Suite' },
  { id: 'cl-045', name: 'Sophia Crane',          title: 'Chief Risk Officer',                      company: 'CrestEx',                    side: 'Client', email: '',                                    phone: '', location: 'San Francisco, CA',  department: 'Risk',            level: 'C-Suite' },
  { id: 'cl-046', name: 'Marcus Ridley',         title: 'Chief Compliance Officer',                company: 'TokenVault',                 side: 'Client', email: '',                                    phone: '', location: 'San Francisco, CA',  department: 'Compliance',      level: 'C-Suite' },
  { id: 'cl-047', name: 'Isabel Fuentes',        title: 'Chief Risk & Compliance Officer',         company: 'CariBank',                   side: 'Client', email: '',                                    phone: '', location: 'San Juan, PR',        department: 'Risk',            level: 'C-Suite' },
  { id: 'cl-048', name: 'Derek Stanton',         title: 'Chief Risk Officer',                      company: 'Horizon Bank',               side: 'Client', email: '',                                    phone: '', location: 'McLean, VA',          department: 'Risk',            level: 'C-Suite' },
  { id: 'cl-049', name: 'Yvonne Castellano',     title: 'Digital & Innovation CRO',                company: 'Pacific National Bank',      side: 'Client', email: '',                                    phone: '', location: 'San Francisco, CA',  department: 'Risk',            level: 'C-Suite' },
  { id: 'cl-050', name: 'Curtis Blackwood',      title: 'Chief Risk Officer',                      company: 'Heartland Regional Bank',    side: 'Client', email: '',                                    phone: '', location: 'Evansville, IN',      department: 'Risk',            level: 'C-Suite' },
  { id: 'cl-051', name: 'Priscilla Ramsey',      title: 'Chief Risk Officer',                      company: 'Keystone Financial Corp',    side: 'Client', email: '',                                    phone: '', location: 'Cleveland, OH',       department: 'Risk',            level: 'C-Suite' },
  { id: 'cl-052', name: 'Dean Parrish',          title: 'Chief Innovation Officer',                company: 'Northern Plains Bank',       side: 'Client', email: 'd.parrish@northernplainsbank.com',    phone: '', location: 'Bismarck, ND',        department: 'Innovation',      level: 'C-Suite' },
  { id: 'cl-053', name: 'Gregory Lawson',        title: 'Chief Risk Officer',                      company: 'Summit Western Bancorp',     side: 'Client', email: '',                                    phone: '', location: 'Salt Lake City, UT',  department: 'Risk',            level: 'C-Suite' },
  { id: 'cl-054', name: 'Amanda Clifford',       title: 'Head of Capital Markets',                 company: 'Summit Western Bancorp',     side: 'Client', email: 'a.clifford@summitwesternbancorp.com', phone: '', location: 'Salt Lake City, UT',  department: 'Capital Markets', level: 'Director' },
  { id: 'cl-055', name: 'Patrick Gallagher',     title: 'Chief Risk Officer',                      company: 'Cornerstone Community Bank', side: 'Client', email: '',                                    phone: '', location: 'Chicago, IL',        department: 'Risk',            level: 'C-Suite' },
  { id: 'cl-056', name: 'Leah Thornton',         title: 'Chief Risk Officer',                      company: 'TreeLine Investments',       side: 'Client', email: '',                                    phone: '', location: 'New York, NY',      department: 'Risk',            level: 'C-Suite' },
  { id: 'cl-057', name: 'Annette Chambers',      title: 'Chief Compliance Officer',                company: 'GlobalEx',                   side: 'Client', email: '',                                    phone: '', location: 'Dubai, UAE',          department: 'Compliance',      level: 'C-Suite' },
  { id: 'cl-058', name: 'Rahul Bose',            title: 'BSA/AML Investigations Lead',             company: 'Sigma Technologies',         side: 'Client', email: '',                                    phone: '', location: 'Menlo Park, CA',      department: 'Financial Crime', level: 'Director' },
  { id: 'cl-059', name: 'Franklin Drew',         title: 'Chief Compliance Officer',                company: 'Ironside Bank',              side: 'Client', email: '',                                    phone: '', location: 'Columbus, OH',        department: 'Compliance',      level: 'C-Suite' },
  { id: 'cl-060', name: 'Claudia Westbrook',     title: 'Chief Compliance Officer',                company: 'Trader Pulse / CryptoPort',  side: 'Client', email: '',                                    phone: '', location: 'Menlo Park, CA',      department: 'Compliance',      level: 'C-Suite' },
  { id: 'cl-061', name: 'Asha Brennan',          title: 'Program Lead, Digital Assets Compliance', company: 'Liberty Financial Group',    side: 'Client', email: '',                                    phone: '', location: 'Fargo, ND',           department: 'Compliance',      level: 'Director' },
  { id: 'cl-062', name: 'Victor Hale',           title: 'SVP Digital Assets & Infrastructure',     company: 'Harvest Bank',               side: 'Client', email: '',                                    phone: '', location: 'Enid, OK',            department: 'Digital Assets',  level: 'SVP' },
  { id: 'cl-063', name: 'Elaine Marsh',          title: 'Chief Financial Officer',                 company: 'Apex Cloud Corp',            side: 'Client', email: '',                                    phone: '', location: 'Mountain View, CA',   department: 'Finance',         level: 'C-Suite' },
  { id: 'cl-064', name: 'Tonya Blackwell',       title: 'Chief Compliance Officer, Payments',      company: 'QuickPay Solutions',         side: 'Client', email: '',                                    phone: '', location: 'Los Altos, CA',       department: 'Compliance',      level: 'C-Suite' },
  { id: 'cl-065', name: 'Sanjay Mirza',          title: 'Chief Risk Officer',                      company: 'LedgerIQ',                   side: 'Client', email: '',                                    phone: '', location: 'London, UK',          department: 'Risk',            level: 'C-Suite' },
  { id: 'cl-066', name: 'Olivia Strauss',        title: 'Chief Compliance Officer',                company: 'PrimeAXS Markets',           side: 'Client', email: '',                                    phone: '', location: 'New York, NY',      department: 'Compliance',      level: 'C-Suite' },
  { id: 'cl-067', name: 'Harold Jennings',       title: 'Chief Risk Officer',                      company: 'Meridian Card Network',      side: 'Client', email: '',                                    phone: '', location: 'New York, NY',      department: 'Risk',            level: 'C-Suite' },
  { id: 'cl-068', name: 'Cody Winters',          title: 'Crypto Risk Manager',                     company: 'Midwest Century Bank',       side: 'Client', email: '',                                    phone: '', location: 'Cincinnati, OH',      department: 'Risk',            level: 'Manager' },
];

export const ENGAGEMENTS: Engagement[] = [
  {
    id: 'ENG-001', client: 'Summit Bridge Bank', industry: 'Banks',
    engagementName: 'AML Program Support & Staff Augmentation',
    businessUnit: 'Consulting', serviceType: 'AML / BSA', status: 'Active',
    partnerId: 'nxg-001', managerId: 'nxg-004',
    teamIds: ['nxg-001', 'nxg-002', 'nxg-003', 'nxg-004', 'nxg-005'],
    clientContactIds: ['cl-001', 'cl-002'],
    revenueK: 480, startDate: '2023-01-01', endDate: '2026-12-31',
    billingArrangement: 'Time & Materials', office: 'New York, NY',
    notes: 'Staff Augmentation (2026); Level 1 alert surge support (2025); ORS Surge Support (2025); Lookback project (2025); ORS Renewal Q1 (2025); 2024 AML Outsourced review; 2023 Targeted TM assessment; 2023 Staff Augmentation; 2023 AML Lookback. In progress: Compliance and DA Support; Fair Lending Analysis; Credit Validation.',
  },
  {
    id: 'ENG-002', client: 'Clearwater Community Bank', industry: 'Banks',
    engagementName: 'Digital Asset Strategy Advisory',
    businessUnit: 'Consulting', serviceType: 'Advisory', status: 'Proposed',
    partnerId: 'nxg-006', managerId: 'nxg-007',
    teamIds: ['nxg-006', 'nxg-007'], clientContactIds: ['cl-003'],
    revenueK: 75, startDate: '2026-01-01', endDate: '',
    billingArrangement: 'Fixed Fee', office: 'Chicago, IL',
    notes: 'Focused on embedded banking and fintech partnerships. No direct digital asset strategy — BaaS and fintech infrastructure play.',
  },
  {
    id: 'ENG-003', client: 'Veriblock Trust', industry: 'Crypto Native Firms (Issuer)',
    engagementName: 'Global AML Independent Testing & Control Assessment',
    businessUnit: 'Consulting', serviceType: 'AML Independent Testing', status: 'Active',
    partnerId: 'nxg-008', managerId: 'nxg-026',
    teamIds: ['nxg-008', 'nxg-026'], clientContactIds: ['cl-004', 'cl-005', 'cl-006'],
    revenueK: 295, startDate: '2023-01-01', endDate: '2026-12-31',
    billingArrangement: 'Time & Materials', office: 'New York, NY',
    notes: 'Global AML Independent Testing + Control Assessment (2026); AML Independent Testing (2024); Independent Issue Validation (2023/2024). In Progress: 2026 OCC MRM Review. Stablecoin issuer with payment processor partnership.',
  },
  {
    id: 'ENG-004', client: 'Fluxpay Inc.', industry: 'Money Transmitters & Payment Processors',
    engagementName: 'AML Model Validation & BSA/AML Independent Testing',
    businessUnit: 'Consulting', serviceType: 'Model Validation', status: 'Active',
    partnerId: 'nxg-009', managerId: 'nxg-026',
    teamIds: ['nxg-009', 'nxg-026'], clientContactIds: ['cl-007', 'cl-008', 'cl-009'],
    revenueK: 230, startDate: '2023-01-01', endDate: '2026-12-31',
    billingArrangement: 'Fixed Fee', office: 'New York, NY',
    notes: 'AML Model Validation (2024 & 2025) + BSA/AML Independent Testing (2023-2025). Licensed money transmitter; global payment automation with crypto payout support.',
  },
  {
    id: 'ENG-005', client: 'Bastion Digital Bank', industry: 'Other',
    engagementName: 'AML & Sanctions Model Validation + Program Assessment',
    businessUnit: 'Consulting', serviceType: 'Model Validation', status: 'Active',
    partnerId: 'nxg-010', managerId: 'nxg-026',
    teamIds: ['nxg-010', 'nxg-026'], clientContactIds: ['cl-011', 'cl-012'],
    revenueK: 365, startDate: '2022-01-01', endDate: '2024-12-31',
    billingArrangement: 'Time & Materials', office: 'Chicago, IL',
    notes: 'AML & Sanctions Model Validation (2024); Program Review and Assessment (2023); Third Party Risk Assessment (2022); BCP/DR Support (2022); AML Program and Control Assessment (2022). Digital asset bank — 100% reserve model.',
  },
  {
    id: 'ENG-006', client: 'Apex Valley Bank', industry: 'Banks',
    engagementName: 'AML Audit',
    businessUnit: 'Audit', serviceType: 'Internal Audit', status: 'Active',
    partnerId: 'nxg-011', managerId: 'nxg-021',
    teamIds: ['nxg-011', 'nxg-021'], clientContactIds: ['cl-013', 'cl-014', 'cl-015'],
    revenueK: 185, startDate: '2019-01-01', endDate: '2026-12-31',
    billingArrangement: 'Fixed Fee', office: 'Dallas, TX',
    notes: 'AML Audit (2026) — In progress; AML Audits (2025, 2020); Internal Audit 2019. Involved in tokenized deposit network initiative.',
  },
  {
    id: 'ENG-007', client: 'Ridgeline Commerce Bank', industry: 'Banks',
    engagementName: 'ECS Tuning, IT Audit & SNC Model Validation',
    businessUnit: 'Audit', serviceType: 'Internal Audit', status: 'Active',
    partnerId: 'nxg-002', managerId: 'nxg-012',
    teamIds: ['nxg-002', 'nxg-012'], clientContactIds: [],
    revenueK: 255, startDate: '2025-01-01', endDate: '2026-12-31',
    billingArrangement: 'Time & Materials', office: 'Dallas, TX',
    notes: '2026 ECS Tuning; 2026 Outsourced IT Internal Audit; 2025 Internal Audit and Compliance Outsourced Audit; SNC Model Validation. Banking services to digital asset firms.',
  },
  {
    id: 'ENG-008', client: 'Keystone National Bank', industry: 'Banks',
    engagementName: 'Financial Crime Audit Program Testing & Support',
    businessUnit: 'Consulting', serviceType: 'Financial Crime', status: 'Active',
    partnerId: 'nxg-013', managerId: 'nxg-003',
    teamIds: ['nxg-013', 'nxg-003'], clientContactIds: ['cl-016'],
    revenueK: 390, startDate: '2025-01-01', endDate: '2026-12-31',
    billingArrangement: 'Time & Materials', office: 'Charlotte, NC',
    notes: 'Financial Crime Audit Program Testing & Support (Current). Developing blockchain-based systems for payments, settlement, and identity.',
  },
  {
    id: 'ENG-009', client: 'Mariner Financial Group', industry: 'Banks',
    engagementName: 'Digital Assets Advisory',
    businessUnit: 'Consulting', serviceType: 'Advisory', status: 'Completed',
    partnerId: 'nxg-011', managerId: 'nxg-007',
    teamIds: ['nxg-011'], clientContactIds: ['cl-017', 'cl-018'],
    revenueK: 200, startDate: '2022-01-01', endDate: '2024-12-31',
    billingArrangement: 'Fixed Fee', office: 'Dallas, TX',
    notes: 'Former client. Tokenized deposits and cross-border payment pilot. Senior leader spoke at institutional digital asset conference.',
  },
  {
    id: 'ENG-010', client: 'Atlas Capital Group', industry: 'Banks',
    engagementName: 'IA Testing & Review + AML Model Validation',
    businessUnit: 'Audit', serviceType: 'Internal Audit', status: 'Active',
    partnerId: 'nxg-029', managerId: 'nxg-003',
    teamIds: ['nxg-029', 'nxg-003'], clientContactIds: ['cl-019'],
    revenueK: 430, startDate: '2023-01-01', endDate: '2026-12-31',
    billingArrangement: 'Time & Materials', office: 'New York, NY',
    notes: 'IA Testing and Review (2025); AML Model Validation (2023); Multiple proposed engagements in progress. Internal tokenization platform.',
  },
  {
    id: 'ENG-011', client: 'Western Frontier Bank', industry: 'Banks',
    engagementName: 'Tax Services',
    businessUnit: 'Tax', serviceType: 'Tax Compliance', status: 'Active',
    partnerId: 'nxg-014', managerId: 'nxg-014',
    teamIds: ['nxg-014'], clientContactIds: ['cl-022'],
    revenueK: 125, startDate: '2021-01-01', endDate: '2024-12-31',
    billingArrangement: 'Fixed Fee', office: 'Phoenix, AZ',
    notes: '2021-2024 Tax services. $90B in assets. Attended Digital Asset Summit.',
  },
  {
    id: 'ENG-012', client: 'Lakeview Financial', industry: 'Banks',
    engagementName: 'Internal Audit + EDD Reviews',
    businessUnit: 'Audit', serviceType: 'Internal Audit', status: 'Active',
    partnerId: 'nxg-015', managerId: 'nxg-019',
    teamIds: ['nxg-015', 'nxg-019'], clientContactIds: ['cl-024'],
    revenueK: 225, startDate: '2024-01-01', endDate: '2026-12-31',
    billingArrangement: 'Time & Materials', office: 'Chicago, IL',
    notes: 'Internal Audit (2024) + EDD Reviews (Current) + Integration project (Current). Participating in pilot for tokenized deposits.',
  },
  {
    id: 'ENG-013', client: 'Midland Heritage Bank', industry: 'Banks',
    engagementName: 'Actimize Fraud Implementation',
    businessUnit: 'Consulting', serviceType: 'System Implementation', status: 'Active',
    partnerId: 'nxg-015', managerId: 'nxg-019',
    teamIds: ['nxg-015', 'nxg-019'], clientContactIds: ['cl-026'],
    revenueK: 180, startDate: '2025-01-01', endDate: '2026-12-31',
    billingArrangement: 'Fixed Fee', office: 'Chicago, IL',
    notes: 'Actimize Fraud Implementation (Current). Network participant for tokenized deposits and blockchain-based settlement.',
  },
  {
    id: 'ENG-014', client: 'Harborview Bank', industry: 'Banks',
    engagementName: 'Actimize System Implementation',
    businessUnit: 'Consulting', serviceType: 'System Implementation', status: 'Active',
    partnerId: 'nxg-016', managerId: 'nxg-003',
    teamIds: ['nxg-016', 'nxg-003'], clientContactIds: ['cl-027', 'cl-028'],
    revenueK: 210, startDate: '2025-01-01', endDate: '2026-12-31',
    billingArrangement: 'Fixed Fee', office: 'Chicago, IL',
    notes: 'Actimize System Implementation (Current). Operates blockchain-based real-time payments platform for instant settlement.',
  },
  {
    id: 'ENG-015', client: 'Rapid Ledger / Apex Bridge', industry: 'Money Transmitters & Payment Processors',
    engagementName: 'Financial Crime Reviews & Digital Asset Investigation',
    businessUnit: 'Consulting', serviceType: 'Financial Crime', status: 'Completed',
    partnerId: 'nxg-008', managerId: 'nxg-027',
    teamIds: ['nxg-008', 'nxg-027'], clientContactIds: ['cl-029', 'cl-030', 'cl-031'],
    revenueK: 170, startDate: '2022-01-01', endDate: '2024-12-31',
    billingArrangement: 'Time & Materials', office: 'New York, NY',
    notes: 'Financial Crime Reviews + Digital Asset Investigation/Reviews. Stablecoin infrastructure; APIs for issuing and moving stablecoins.',
  },
  {
    id: 'ENG-016', client: 'PrimeEx Digital', industry: 'Crypto Native Firms (Exchange)',
    engagementName: 'AML Remediation Validation & BSA Independent Testing',
    businessUnit: 'Consulting', serviceType: 'AML Independent Testing', status: 'Active',
    partnerId: 'nxg-009', managerId: 'nxg-026',
    teamIds: ['nxg-009', 'nxg-026'], clientContactIds: ['cl-034'],
    revenueK: 200, startDate: '2024-01-01', endDate: '2026-12-31',
    billingArrangement: 'Time & Materials', office: 'New York, NY',
    notes: '2025 AML Remediation Validation Testing + BSA Independent Testing (2026).',
  },
  {
    id: 'ENG-017', client: 'WaveSettle', industry: 'Crypto Native Firms (Infra Provider)',
    engagementName: 'BSA/AML Independent Testing + 504 Readiness Assessment',
    businessUnit: 'Consulting', serviceType: 'AML Independent Testing', status: 'Active',
    partnerId: 'nxg-008', managerId: 'nxg-026',
    teamIds: ['nxg-008', 'nxg-026'], clientContactIds: ['cl-037', 'cl-038'],
    revenueK: 215, startDate: '2025-01-01', endDate: '2026-12-31',
    billingArrangement: 'Fixed Fee', office: 'New York, NY',
    notes: 'BSA/AML Independent Testing + 504 Readiness Assessment (2026). Cross-border payments and liquidity solutions.',
  },
  {
    id: 'ENG-018', client: 'IronSafe Digital', industry: 'Crypto Native Firms (Infra Provider)',
    engagementName: 'Attestation Reporting',
    businessUnit: 'Audit', serviceType: 'Attestation', status: 'Active',
    partnerId: 'nxg-017', managerId: 'nxg-017',
    teamIds: ['nxg-017'], clientContactIds: ['cl-039'],
    revenueK: 145, startDate: '2026-01-01', endDate: '2026-12-31',
    billingArrangement: 'Fixed Fee', office: 'New York, NY',
    notes: 'Attestation Reporting (2026). Institutional crypto custody, wallet infrastructure, settlement, tokenized assets and staking.',
  },
  {
    id: 'ENG-019', client: 'NovaBanc', industry: 'Banks',
    engagementName: 'IT Assurance SOC Exam + BSA Audit',
    businessUnit: 'Audit', serviceType: 'IT Assurance / SOC', status: 'Active',
    partnerId: 'nxg-018', managerId: 'nxg-019',
    teamIds: ['nxg-018', 'nxg-019'], clientContactIds: ['cl-041'],
    revenueK: 190, startDate: '2025-01-01', endDate: '2026-12-31',
    billingArrangement: 'Fixed Fee', office: 'Chicago, IL',
    notes: 'IT Assurance SOC Exam (2026) + Compliance & Bank Secrecy Act Audit (2026). Digital asset exposure via banking and investment platform.',
  },
  {
    id: 'ENG-020', client: 'Pinnacle National Bank', industry: 'Banks',
    engagementName: 'Actimize System Implementation',
    businessUnit: 'Consulting', serviceType: 'System Implementation', status: 'Active',
    partnerId: 'nxg-015', managerId: 'nxg-019',
    teamIds: ['nxg-015', 'nxg-019'], clientContactIds: ['cl-042'],
    revenueK: 240, startDate: '2024-01-01', endDate: '2025-12-31',
    billingArrangement: 'Fixed Fee', office: 'Chicago, IL',
    notes: 'Actimize System Implementation (2025). Blockchain/digital asset initiatives through institutional partnerships.',
  },
  {
    id: 'ENG-021', client: 'VoltChain', industry: 'Crypto Native Firms (Infra Provider)',
    engagementName: 'Digital Asset Investigation & Reviews',
    businessUnit: 'Consulting', serviceType: 'Advisory', status: 'Active',
    partnerId: 'nxg-008', managerId: 'nxg-027',
    teamIds: ['nxg-008', 'nxg-027'], clientContactIds: ['cl-043'],
    revenueK: 125, startDate: '2025-01-01', endDate: '2026-12-31',
    billingArrangement: 'Time & Materials', office: 'New York, NY',
    notes: 'Digital Asset Investigation/Reviews. Lightning Network infrastructure for Bitcoin payments.',
  },
  {
    id: 'ENG-022', client: 'Pacific National Bank', industry: 'Banks',
    engagementName: 'Internal Audit',
    businessUnit: 'Audit', serviceType: 'Internal Audit', status: 'Active',
    partnerId: 'nxg-020', managerId: 'nxg-020',
    teamIds: ['nxg-020'], clientContactIds: ['cl-049'],
    revenueK: 255, startDate: '2025-01-01', endDate: '2026-12-31',
    billingArrangement: 'Time & Materials', office: 'Charlotte, NC',
    notes: 'Internal Audit (Current). Traditional banking; limited crypto-related activity historically.',
  },
  {
    id: 'ENG-023', client: 'Strata Financial', industry: 'Banks',
    engagementName: 'Defined Benefits Plan Audit + Health & Welfare Plans Audit',
    businessUnit: 'Audit', serviceType: 'Internal Audit', status: 'Active',
    partnerId: 'nxg-021', managerId: 'nxg-021',
    teamIds: ['nxg-021'], clientContactIds: [],
    revenueK: 90, startDate: '2025-01-01', endDate: '2026-12-31',
    billingArrangement: 'Fixed Fee', office: 'Dallas, TX',
    notes: 'Defined Benefits Plan Audit + Health & Welfare Plans Audit (Current). Internal blockchain solutions for cross-border DLT settlement.',
  },
  {
    id: 'ENG-024', client: 'Heartland Regional Bank', industry: 'Other',
    engagementName: 'ServiceNow IRM Deployment + NACHA Audit',
    businessUnit: 'Consulting', serviceType: 'System Implementation', status: 'Active',
    partnerId: 'nxg-022', managerId: 'nxg-022',
    teamIds: ['nxg-022'], clientContactIds: ['cl-050'],
    revenueK: 180, startDate: '2023-01-01', endDate: '2026-12-31',
    billingArrangement: 'Fixed Fee', office: 'Chicago, IL',
    notes: 'ServiceNow IRM Deployment (Current) + NACHA Audit (2023). BaaS and neobank platform supporting crypto-native/Web3 companies.',
  },
  {
    id: 'ENG-025', client: 'Keystone Financial Corp', industry: 'Banks',
    engagementName: 'MRM Data Validation + WLS Full Scope Model Validation',
    businessUnit: 'Consulting', serviceType: 'Model Validation', status: 'Active',
    partnerId: 'nxg-002', managerId: 'nxg-026',
    teamIds: ['nxg-002', 'nxg-026'], clientContactIds: ['cl-051'],
    revenueK: 275, startDate: '2024-01-01', endDate: '2025-12-31',
    billingArrangement: 'Time & Materials', office: 'New York, NY',
    notes: 'MRM Data Validation (2024) + WLS Full Scope Model Validation (2025). Founding member of tokenized deposit network.',
  },
  {
    id: 'ENG-026', client: 'Summit Western Bancorp', industry: 'Banks',
    engagementName: 'Risk Advisory + Stablecoin Feasibility Assessment',
    businessUnit: 'Consulting', serviceType: 'Risk Advisory', status: 'Active',
    partnerId: 'nxg-010', managerId: 'nxg-026',
    teamIds: ['nxg-010', 'nxg-026'], clientContactIds: ['cl-053', 'cl-054'],
    revenueK: 195, startDate: '2025-01-01', endDate: '2026-12-31',
    billingArrangement: 'Fixed Fee', office: 'Chicago, IL',
    notes: 'Risk Advisory (Current). Assessed feasibility, risk, and regulatory implications of launching a stablecoin for bank-to-bank payments. Presented on stablecoin benefits January 2026.',
  },
  {
    id: 'ENG-027', client: 'TreeLine Investments', industry: 'Banks',
    engagementName: 'BaaS Program Advisory',
    businessUnit: 'Consulting', serviceType: 'Advisory', status: 'Active',
    partnerId: 'nxg-006', managerId: 'nxg-007',
    teamIds: ['nxg-006', 'nxg-007'], clientContactIds: ['cl-056'],
    revenueK: 135, startDate: '2025-01-01', endDate: '2025-12-31',
    billingArrangement: 'Fixed Fee', office: 'Chicago, IL',
    notes: 'BaaS Program Advisory (2025). Tokenized asset products, digital funds, blockchain-based issuance.',
  },
  {
    id: 'ENG-028', client: 'GlobalEx', industry: 'Crypto Native Firms (Issuer)',
    engagementName: 'DFS 504 Model Validation + Internal Audit Program',
    businessUnit: 'Consulting', serviceType: 'Model Validation', status: 'Active',
    partnerId: 'nxg-003', managerId: 'nxg-027',
    teamIds: ['nxg-003', 'nxg-027'], clientContactIds: ['cl-057'],
    revenueK: 315, startDate: '2025-01-01', endDate: '2026-12-31',
    billingArrangement: 'Time & Materials', office: 'New York, NY',
    notes: '2026 DFS 504 Model Validation + 2026 Internal Audit Program and Risk Assessment. Global crypto exchange.',
  },
  {
    id: 'ENG-029', client: 'Ironside Bank', industry: 'Other',
    engagementName: 'Risk & Controls Consulting + TM Program Staff Augmentation',
    businessUnit: 'Consulting', serviceType: 'Risk Advisory', status: 'Active',
    partnerId: 'nxg-015', managerId: 'nxg-028',
    teamIds: ['nxg-015', 'nxg-028'], clientContactIds: ['cl-059'],
    revenueK: 200, startDate: '2025-01-01', endDate: '2026-12-31',
    billingArrangement: 'Time & Materials', office: 'Chicago, IL',
    notes: 'Risk & Controls Consulting (Current) + TM Program Staff Augmentation (Current) + Proposing AML & Sanctions Independent Assessment. Newly chartered OCC national bank targeting crypto and tech clients.',
  },
  {
    id: 'ENG-030', client: 'Trader Pulse / CryptoPort', industry: 'Crypto Native Firms (Exchange)',
    engagementName: 'Operational Accounting Transformation + Outsourced Internal Audit',
    businessUnit: 'Audit', serviceType: 'Internal Audit', status: 'Active',
    partnerId: 'nxg-024', managerId: 'nxg-025',
    teamIds: ['nxg-024', 'nxg-025'], clientContactIds: ['cl-060'],
    revenueK: 225, startDate: '2025-01-01', endDate: '2026-12-31',
    billingArrangement: 'Time & Materials', office: 'Chicago, IL',
    notes: 'Operational Accounting/Finance Transformation (2026) + Outsourced Internal Audit (Current). CryptoPort operates a regulated crypto exchange; Trader Pulse offers retail brokerage-based crypto access.',
  },
  {
    id: 'ENG-031', client: 'ClearSend Payments', industry: 'Banks',
    engagementName: 'TM & Sanctions Model Validation',
    businessUnit: 'Consulting', serviceType: 'Model Validation', status: 'Active',
    partnerId: 'nxg-009', managerId: 'nxg-026',
    teamIds: ['nxg-009', 'nxg-026'], clientContactIds: [],
    revenueK: 180, startDate: '2026-01-01', endDate: '2026-12-31',
    billingArrangement: 'Fixed Fee', office: 'New York, NY',
    notes: 'TM & Sanctions Model Validation (2026). Payment processing and digital wallet services including fiat on/off-ramps for crypto.',
  },
  {
    id: 'ENG-032', client: 'Fulcrum Bank Group', industry: 'Banks',
    engagementName: 'AML Compliance Internal Audit + Model Validation',
    businessUnit: 'Audit', serviceType: 'Internal Audit', status: 'Active',
    partnerId: 'nxg-002', managerId: 'nxg-026',
    teamIds: ['nxg-002', 'nxg-026'], clientContactIds: [],
    revenueK: 160, startDate: '2024-01-01', endDate: '2026-12-31',
    billingArrangement: 'Fixed Fee', office: 'New York, NY',
    notes: 'AML Compliance Internal Audit (Current) + Model Validation (2024). Now includes settlement with stablecoin and blockchain analytics providers. OCC-chartered bank.',
  },
  {
    id: 'ENG-033', client: 'Liberty Financial Group', industry: 'Other',
    engagementName: 'BSA Internal Audit',
    businessUnit: 'Audit', serviceType: 'Internal Audit', status: 'Active',
    partnerId: 'nxg-026', managerId: 'nxg-026',
    teamIds: ['nxg-026'], clientContactIds: ['cl-061'],
    revenueK: 125, startDate: '2026-01-01', endDate: '2026-12-31',
    billingArrangement: 'Fixed Fee', office: 'New York, NY',
    notes: 'BSA Internal Audit (2026). Provides fiat accounts and payment rails to crypto-native and Web3 companies.',
  },
  {
    id: 'ENG-034', client: 'Harvest Bank', industry: 'Banks',
    engagementName: 'AML & Sanctions Audit',
    businessUnit: 'Audit', serviceType: 'Internal Audit', status: 'Active',
    partnerId: 'nxg-026', managerId: 'nxg-026',
    teamIds: ['nxg-026'], clientContactIds: ['cl-062'],
    revenueK: 135, startDate: '2026-01-01', endDate: '2026-12-31',
    billingArrangement: 'Fixed Fee', office: 'New York, NY',
    notes: 'AML & Sanctions Audit (2026). Banking services to fintech and crypto firms via partnerships.',
  },
  {
    id: 'ENG-035', client: 'Apex Cloud Corp', industry: 'Other',
    engagementName: 'AML & Sanctions Audit',
    businessUnit: 'Audit', serviceType: 'Internal Audit', status: 'Active',
    partnerId: 'nxg-025', managerId: 'nxg-025',
    teamIds: ['nxg-025'], clientContactIds: ['cl-063'],
    revenueK: 360, startDate: '2026-01-01', endDate: '2026-12-31',
    billingArrangement: 'Time & Materials', office: 'Chicago, IL',
    notes: 'AML & Sanctions Audit (2026). Cloud payments platform — blockchain technology exploration.',
  },
  {
    id: 'ENG-036', client: 'QuickPay Solutions', industry: 'Money Transmitters & Payment Processors',
    engagementName: 'AML Compliance Independent Testing',
    businessUnit: 'Consulting', serviceType: 'AML Independent Testing', status: 'Active',
    partnerId: 'nxg-026', managerId: 'nxg-026',
    teamIds: ['nxg-026'], clientContactIds: ['cl-064'],
    revenueK: 145, startDate: '2025-01-01', endDate: '2025-12-31',
    billingArrangement: 'Fixed Fee', office: 'New York, NY',
    notes: 'AML Compliance Independent Testing (2025). Payment orchestration platform.',
  },
  {
    id: 'ENG-037', client: 'LedgerIQ', industry: 'Money Transmitters & Payment Processors',
    engagementName: 'AML Compliance Advisory Program',
    businessUnit: 'Consulting', serviceType: 'Advisory', status: 'Active',
    partnerId: 'nxg-009', managerId: 'nxg-026',
    teamIds: ['nxg-009', 'nxg-026'], clientContactIds: ['cl-065'],
    revenueK: 115, startDate: '2025-01-01', endDate: '2025-12-31',
    billingArrangement: 'Fixed Fee', office: 'New York, NY',
    notes: 'AML Compliance Advisory Program (2025). Crypto accounting and data infrastructure for financial institutions.',
  },
  {
    id: 'ENG-038', client: 'PrimeAXS Markets', industry: 'Crypto Native Firms (Infra Provider)',
    engagementName: 'Assurance Special Project',
    businessUnit: 'Audit', serviceType: 'Attestation', status: 'Active',
    partnerId: 'nxg-017', managerId: 'nxg-017',
    teamIds: ['nxg-017'], clientContactIds: ['cl-066'],
    revenueK: 125, startDate: '2025-01-01', endDate: '2025-12-31',
    billingArrangement: 'Fixed Fee', office: 'New York, NY',
    notes: 'Assurance Special Project. Institutional-focused non-custodial crypto exchange.',
  },
  {
    id: 'ENG-039', client: 'Meridian Card Network', industry: 'Payments Network',
    engagementName: 'Assurance Planning',
    businessUnit: 'Audit', serviceType: 'Internal Audit', status: 'Active',
    partnerId: 'nxg-013', managerId: 'nxg-017',
    teamIds: ['nxg-013', 'nxg-017'], clientContactIds: ['cl-067'],
    revenueK: 210, startDate: '2025-01-01', endDate: '2026-12-31',
    billingArrangement: 'Time & Materials', office: 'Charlotte, NC',
    notes: 'Assurance Planning. Global card network with tested crypto-linked features.',
  },
  {
    id: 'ENG-040', client: 'Midwest Century Bank', industry: 'Banks',
    engagementName: 'AML Policy & Digital Asset Engagement',
    businessUnit: 'Consulting', serviceType: 'AML / BSA', status: 'Active',
    partnerId: 'nxg-030', managerId: 'nxg-003',
    teamIds: ['nxg-030', 'nxg-003', 'nxg-007'], clientContactIds: ['cl-068'],
    revenueK: 155, startDate: '2026-01-01', endDate: '2026-12-31',
    billingArrangement: 'Time & Materials', office: 'Columbus, OH',
    notes: 'Crypto Risk Manager engaged on AML policy issues with GENIUS and Clarity Acts (Q2 2026). Bank in early stages of digital asset engagement.',
  },
  {
    id: 'ENG-041', client: 'CariBank', industry: 'Crypto Native Firms',
    engagementName: 'Third-Party Risk Assessment + Security Compliance Staff Aug',
    businessUnit: 'Consulting', serviceType: 'Risk Advisory', status: 'Active',
    partnerId: 'nxg-023', managerId: 'nxg-023',
    teamIds: ['nxg-023'], clientContactIds: ['cl-047'],
    revenueK: 155, startDate: '2025-01-01', endDate: '2026-12-31',
    billingArrangement: 'Time & Materials', office: 'New York, NY',
    notes: 'Third-Party Risk Assessment (Current) + Staff Augmentation Security Compliance (Current). Regulated crypto-friendly bank.',
  },

  // Prospects (no active engagement)
  {
    id: 'ENG-042', client: 'Orion Stablecoin', industry: 'Crypto Native Firms (Issuer)',
    engagementName: 'AML Program Assessment (Proposed)',
    businessUnit: 'Consulting', serviceType: 'AML Independent Testing', status: 'Proposed',
    partnerId: 'nxg-011', managerId: 'nxg-026',
    teamIds: ['nxg-011'], clientContactIds: ['cl-036'],
    revenueK: 100, startDate: '2026-06-01', endDate: '',
    billingArrangement: 'Fixed Fee', office: 'Dallas, TX',
    notes: 'Kevin Delano has a contact. USDC-equivalent stablecoin issuer and infrastructure provider.',
  },
  {
    id: 'ENG-043', client: 'TokenVault', industry: 'Crypto Native Firms',
    engagementName: 'Compliance Program Review (Proposed)',
    businessUnit: 'Consulting', serviceType: 'Advisory', status: 'Proposed',
    partnerId: 'nxg-003', managerId: 'nxg-009',
    teamIds: ['nxg-003'], clientContactIds: ['cl-046'],
    revenueK: 120, startDate: '2026-06-01', endDate: '',
    billingArrangement: 'Fixed Fee', office: 'New York, NY',
    notes: 'Not currently a client. Global crypto exchange — spot, derivatives, custody, staking, fiat on/off-ramps.',
  },
  {
    id: 'ENG-044', client: 'Pulsar Finance', industry: 'Money Transmitters & Payment Processors',
    engagementName: 'AML Program Review (Proposed)',
    businessUnit: 'Consulting', serviceType: 'AML Independent Testing', status: 'Proposed',
    partnerId: 'nxg-009', managerId: 'nxg-026',
    teamIds: ['nxg-009'], clientContactIds: ['cl-035'],
    revenueK: 95, startDate: '2026-07-01', endDate: '',
    billingArrangement: 'Fixed Fee', office: 'New York, NY',
    notes: 'Recently proposed. EU-licensed fintech with retail crypto trading and custody.',
  },
  {
    id: 'ENG-045', client: 'Vaultstone Digital', industry: 'Crypto Native Firms (Infra Provider)',
    engagementName: 'Compliance Program Assessment (Proposed)',
    businessUnit: 'Consulting', serviceType: 'Advisory', status: 'Proposed',
    partnerId: 'nxg-008', managerId: 'nxg-017',
    teamIds: ['nxg-008'], clientContactIds: ['cl-040'],
    revenueK: 90, startDate: '2026-07-01', endDate: '',
    billingArrangement: 'Fixed Fee', office: 'New York, NY',
    notes: 'No active engagement. Federally chartered crypto bank — custody, trading, staking, settlement.',
  },
  {
    id: 'ENG-046', client: 'CrestEx', industry: 'Crypto Native Firms (Exchange)',
    engagementName: 'AML Independent Testing (Proposed)',
    businessUnit: 'Consulting', serviceType: 'AML Independent Testing', status: 'Proposed',
    partnerId: 'nxg-009', managerId: 'nxg-026',
    teamIds: ['nxg-009'], clientContactIds: ['cl-045'],
    revenueK: 110, startDate: '2026-08-01', endDate: '',
    billingArrangement: 'Fixed Fee', office: 'New York, NY',
    notes: 'Not currently a client. Global crypto exchange pursuing US banking charter and expanding institutional offerings.',
  },
];
